// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6iREb_3Jwsr9-eAuUr1wRe1Y59rXX054',
    appId: '1:632049552762:web:be2312c0eb6d00d1ed9ac3',
    messagingSenderId: '632049552762',
    projectId: 'parchapp-852e8',
    authDomain: 'parchapp-852e8.firebaseapp.com',
    storageBucket: 'parchapp-852e8.firebasestorage.app',
    measurementId: 'G-CERX88VNZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUhtQ4ORAlm_BA3D3LbGwlNwqWXFgjUZk',
    appId: '1:632049552762:android:1b5b1648ab9cf29ced9ac3',
    messagingSenderId: '632049552762',
    projectId: 'parchapp-852e8',
    storageBucket: 'parchapp-852e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCghCusEUrRDX-ljRY9WquKgBcNN8qLCk4',
    appId: '1:632049552762:ios:be4aa82a4e855c8ded9ac3',
    messagingSenderId: '632049552762',
    projectId: 'parchapp-852e8',
    storageBucket: 'parchapp-852e8.firebasestorage.app',
    iosBundleId: 'com.example.parchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCghCusEUrRDX-ljRY9WquKgBcNN8qLCk4',
    appId: '1:632049552762:ios:be4aa82a4e855c8ded9ac3',
    messagingSenderId: '632049552762',
    projectId: 'parchapp-852e8',
    storageBucket: 'parchapp-852e8.firebasestorage.app',
    iosBundleId: 'com.example.parchapp',
  );
}
